<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="buli" name="com.trustkernel.kpp.api.testcase.TimeOutTest" tests="2" failures="0" timestamp="27 九月 2020 09:15:52 GMT" time="4.031" errors="1">
  <testcase name="testFailed" time="2.015" classname="com.trustkernel.kpp.api.testcase.TimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.trustkernel.kpp.api.testcase.TimeOutTest.testFailed() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.trustkernel.kpp.api.testcase.TimeOutTest.testFailed() didn't finish within the time-out 2000
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testFailed -->
  <testcase name="testSuccess" time="2.016" classname="com.trustkernel.kpp.api.testcase.TimeOutTest"/>
</testsuite> <!-- com.trustkernel.kpp.api.testcase.TimeOutTest -->
