<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="buli" ignored="0" name="TimeOutTest" tests="2" failures="1" timestamp="27 九月 2020 09:15:52 GMT" time="4.047" errors="0">
  <testcase name="testFailed" time="2.015" classname="com.trustkernel.kpp.api.testcase.TimeOutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.trustkernel.kpp.api.testcase.TimeOutTest.testFailed() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.trustkernel.kpp.api.testcase.TimeOutTest.testFailed() didn't finish within the time-out 2000
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testFailed -->
  <testcase name="testSuccess" time="2.016" classname="com.trustkernel.kpp.api.testcase.TimeOutTest"/>
</testsuite> <!-- TimeOutTest -->
